const SHOW_LOADING = "SHOW_LOADING";
const HIDE_LOADING = "HIDE_LOADING";
const SHOW_ROLES = "SHOW_ROLES";
const LOGIN_STARTED = "LOGIN_STARTED";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGIN_NOTSTARTED = "LOGIN_NOTSTARTED";
const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
const ERROR = "ERROR";
const VIEW_FILE_DETAILS = "VIEW_FILE_DETAILS";
const GET_ALL_FILES_DETAILS = "GET_ALL_FILES_DETAILS";

const SIGNUP_STARTED = "SIGNUP_STARTED";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAILED = "SIGNUP_FAILED";
const SIGNUP_NOTSTARTED = "SIGNUP_NOTSTARTED";

const GET_TOTAL_RECORDS_COUNT = "GET_TOTAL_RECORDS_COUNT";
const USER_PROFILE_FETCH_SUCCESS = "USER_PROFILE_FETCH_SUCCESS";
const USER_PROFILE_FETCH_FAILED = "USER_PROFILE_FETCH_FAILED";

const GET_A_TOUR_STARTED = "GET_A_TOUR_STARTED";
const GET_A_TOUR_SUCCESS = "GET_A_TOUR_SUCCESS";
const GET_A_TOUR_FAILED = "GET_A_TOUR_FAILED";
const GET_A_TOUR_NOTSTARTED = "GET_A_TOUR_NOTSTARTED";

const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_STARTED = "CHANGE_PASSWORD_STARTED";
const CHANGE_PASSWORD_NOTSTARTED = "CHANGE_PASSWORD_NOTSTARTED";
const DELETE_DASHBOARD_FAILED = "DELETE_DASHBOARD_FAILED";
const DELETE_DASHBOARD_SUCCESS = "DELETE_DASHBOARD_SUCCESS";
const DELETE_DASHBOARD_STARTED = "DELETE_DASHBOARD_STARTED";
const DELETE_DASHBOARD_NOTSTARTED = "DELETE_DASHBOARD_NOTSTARTED";

const GET_TOURS_STARTED = "GET_TOURS_STARTED";
const GET_TOURS_SUCCESS = "GET_TOURS_SUCCESS";
const GET_TOURS_FAILED = "GET_TOURS_FAILED";
const GET_TOURS_NOTSTARTED = "GET_TOURS_NOTSTARTED";

export {
  SHOW_ROLES,
  SHOW_LOADING,
  HIDE_LOADING,

  ERROR,
  UPDATE_SUBSCRIPTION,
  VIEW_FILE_DETAILS,
  GET_ALL_FILES_DETAILS,

  GET_TOTAL_RECORDS_COUNT,
  USER_PROFILE_FETCH_SUCCESS,
  USER_PROFILE_FETCH_FAILED,

  CHANGE_PASSWORD_FAILED,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_STARTED,
  CHANGE_PASSWORD_NOTSTARTED,
  DELETE_DASHBOARD_NOTSTARTED,
  DELETE_DASHBOARD_SUCCESS,
  DELETE_DASHBOARD_STARTED,
  DELETE_DASHBOARD_FAILED,

  GET_TOURS_STARTED,
  GET_TOURS_SUCCESS,
  GET_TOURS_FAILED,
  GET_TOURS_NOTSTARTED,
  SIGNUP_STARTED,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  SIGNUP_NOTSTARTED,
  LOGIN_STARTED,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGIN_NOTSTARTED,
  
  GET_A_TOUR_STARTED,
  GET_A_TOUR_SUCCESS,
  GET_A_TOUR_FAILED,
  GET_A_TOUR_NOTSTARTED,
};
